# Generated by Django 5.2.4 on 2025-07-10 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_birth_day_profile_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='birth_day',
            new_name='birth_date',
        ),
    ]
