# Generated by Django 5.2.4 on 2025-09-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_favoritegame'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='api_request_count',
            field=models.IntegerField(default=0),
        ),
    ]
