{
 "title": "GameHub",
 "description": "monitoring dashboard for BackEnd, FrontEnd, DataBase and Caching server",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"gamehub-backend\"}",
     "legendFormat": "Backend"
    },
    { "expr": "pg_up", "legendFormat": "PostgreSQL" },
    {
     "expr": "up{job=\"prometheus\"}",
     "legendFormat": "Prometheus"
    },
    {
     "expr": "up{job=\"grafana\"}",
     "legendFormat": "Grafana"
    },
    {
     "expr": "up{job=\"node_exporter\"}",
     "legendFormat": "node-exporter"
    },
    {
     "expr": "up{job=\"gamehub-postgres-exporter\"}",
     "legendFormat": "Postgres-Exporter"
    }
   ]
  },
  { "title": "DataBase", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Table (api)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 20, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_stat_user_tables_n_tup_ins{relname=\"api_game\"}",
     "legendFormat": "Games"
    },
    {
     "expr": "pg_stat_user_tables_n_tup_ins{relname=\"api_genre\"}",
     "legendFormat": "Genres"
    },
    {
     "expr": "pg_stat_user_tables_n_tup_ins{relname=\"api_gamescreenshot\"}",
     "legendFormat": "Game Screenshots"
    },
    {
     "expr": "pg_stat_user_tables_n_tup_ins{relname=\"api_platform\"}",
     "legendFormat": "Platforms"
    }
   ]
  },
  {
   "title": "Registered Users",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_stat_user_tables_n_tup_ins{relname=\"core_user\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Backend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "APIs latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum(rate(django_http_requests_total_by_view_transport_method_total{view!=\"prometheus-django-metrics\"}[5m])) by(view)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Node Exporter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "ceil(node_memory_MemTotal_bytes / 1000000)",
     "legendFormat": "Total memory (MB)"
    },
    {
     "expr": "ceil(node_memory_MemTotal_bytes / 1000000) - ceil(node_memory_MemAvailable_bytes / 1000000)",
     "legendFormat": "Memory used (MB)"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 22 },
   "targets": [
    {
     "expr": "ceil(node_memory_SwapTotal_bytes / 1000000)",
     "legendFormat": "Total (MB)"
    },
    {
     "expr": "ceil(node_memory_SwapCached_bytes / 1000000)",
     "legendFormat": "Used (MB)"
    }
   ]
  },
  {
   "title": "CPU Total Seconds (per CPU)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "avg by(cpu) (rate(node_cpu_seconds_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}