.build_rules:
  stage: build
  environment:
    name: prod
  tags:
    - build

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build backend:
  extends: .build_rules
  rules:
    - changes:
        - "backend/**/*"
        - "kubernetes/charts/backend/**/*"  
        - "pipelines/build.yml"  
  script:
    - docker build ./backend -t $CI_REGISTRY/root/gamehub/gamehub-backend:$CI_COMMIT_SHORT_SHA

    - docker push $CI_REGISTRY/root/gamehub/gamehub-backend:$CI_COMMIT_SHORT_SHA

build frontend:
  extends: .build_rules
  rules:
    - changes:
        - "frontend/**/*"  
        - "kubernetes/charts/backend/**/*"  
        - "pipelines/build.yml"  
  script:    
    - docker build 
      --build-arg VITE_BASE_URL=$VITE_BASE_URL 
      ./frontend -t $CI_REGISTRY/root/gamehub/gamehub-frontend:$CI_COMMIT_SHORT_SHA

    - docker push $CI_REGISTRY/root/gamehub/gamehub-frontend:$CI_COMMIT_SHORT_SHA